name: artemis_test
description: artemis_test

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.13.3
  json_annotation: ^4.0.1
  meta: ^1.3.0 # only if you have non nullable fields
  gql: ^0.13.0
  graphql: ^5.0.0
  json_serializable: ^4.1.4

dev_dependencies:
  build_runner: ^2.1.1
  artemis: ^7.1.1-beta.1
